// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDd_dDoBS_UvIsPLdc1Fsckgh-Ka_Qvho',
    appId: '1:775521520805:web:e8c2f8331b27f0ceec114c',
    messagingSenderId: '775521520805',
    projectId: 'chat-app-6254f',
    authDomain: 'chat-app-6254f.firebaseapp.com',
    storageBucket: 'chat-app-6254f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb7dP1iILfOnYKhl0arYGcwI_cXFPnKe8',
    appId: '1:775521520805:android:286061bfe6960507ec114c',
    messagingSenderId: '775521520805',
    projectId: 'chat-app-6254f',
    storageBucket: 'chat-app-6254f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQtWIRqI0Flt8wUPlC227Ai8_lpwcSuU',
    appId: '1:775521520805:ios:33ff1d6c17edb6f0ec114c',
    messagingSenderId: '775521520805',
    projectId: 'chat-app-6254f',
    storageBucket: 'chat-app-6254f.appspot.com',
    iosClientId: '775521520805-auib8e0bvfta2ant0h44ffp4i99pvn5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQtWIRqI0Flt8wUPlC227Ai8_lpwcSuU',
    appId: '1:775521520805:ios:33ff1d6c17edb6f0ec114c',
    messagingSenderId: '775521520805',
    projectId: 'chat-app-6254f',
    storageBucket: 'chat-app-6254f.appspot.com',
    iosClientId: '775521520805-auib8e0bvfta2ant0h44ffp4i99pvn5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
